DATA_DIR='/data/var/opt'
TABLEAU_VERSION='2022.1'
TABLEAU_BUILD_NUMBER='3'

TABLEAU_TSM_USER=adm-tab
TABLEAU_TSM_USER_PASSWORD=Mydral2018

TABLEAU_SRV_ADM_USER=adm-tab
TABLEAU_SRV_ADM_USER_PASSWORD=Mydral2018

TABLEAU_PG_READONLY_USER=readonly
TABLEAU_PG_READONLY_USER_PASSWORD=Mydral2018
